### ISSUE TITLE
Cotizacion

### ISSUE THREAD

**Issue by Sisterno** [nidhogg-spec/SGAET#51]
- Cambiar tipo de documento a selector - listo
- Sumar pasajaero para generar Npasajeros - listo
-  Aumentar, sin edicion, vista de datos de programa turistico - listo
-  ver si la suma total no es se generar al seleccionar el programa turistico
- Aqui si aparecen todos los productos de todos los proveedores >:v - listo
- Al guardar, nunca termina de cargar. Revisar el res de las apis y ver si se esta devoviendo algo - listo
-

**Comment by Sisterno** [comment]
Obtener datos de clientes cooporativos y mostrarlos

**Comment by nidhogg-spec** [comment]
Terminado por el momento falta corregir el punto 4 si alguien se le ocurre una idea innovadora o en el futuro encontramos como corregir reabrir issue
